export const airports = [
    {code: 'KAT', city:'Katowice', country: 'Poland', region: 'Europe'},
    {code: 'WAW', city:'Warsaw', country: 'Poland', region: 'Europe'},
    {code: 'WRO', city:'Wrocław', country: 'Poland', region: 'Europe'},
    {code: 'LHR', city:'London', country: 'United Kingdom', region: 'Europe'},
    {code: 'AMS', city:'Amsterdam', country: 'Holland', region: 'Europe'},
    {code: 'MAD', city:'Madrid', country: 'Spain', region: 'Europe'},
    {code: 'LIS', city:'Lisboa', country: 'Portugal', region: 'Europe'},
    {code: 'PAR', city:'Paris', country: 'France', region: 'Europe'},
    {code: 'HND', city:'Tokyo', country: 'Japan', region: 'Asia'},
    {code: 'DXB', city:'Dubai', country: 'United Arab Emirates', region: 'Asia'},    
    {code: 'JFK', city:'New York', country: 'USA', region: 'Americas'},
    {code: 'NYC', city:'New York', country: 'USA', region: 'Americas'},
    {code: 'YYZ', city:'Toronto', country: 'Canada', region: 'Americas'},
]