export let FLIGHTS = [
  {
    id: 1,
    name: "American Airlines",
    way: "roundtrip",
    totaltime: "1h 20m",
    departure: "19:35",
    arriving: "20:55",
    from: "LHR",
    to: "AMS",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/aairlines-logo.jpg",
    price: 100
  },
  {
    id: 2,
    name: "Air Canada",
    way: "roundtrip",
    totaltime: "2h 30m",
    departure: "13:10",
    arriving: "14:40",
    from: "LHR",
    to: "AMS",
    steps: "Nonstop",
    airplane: "Airbus A380",
    class: "Business",
    logo: "assets/img/flight/thumb/aircanada-logo.jpg",
    price: 320
  },
  {
    id: 3,
    name: "British Airways",
    way: "roundtrip",
    totaltime: "4h 00m",
    departure: "14:15",
    arriving: "18:15",
    from: "LHR",
    to: "NYC",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/britishairways-logo.jpg",
    price: 270.50
  },
  {
    id: 4,
    name: "LOT",
    way: "roundtrip",
    totaltime: "0h 50m",
    departure: "19:35",
    arriving: "20:25",
    from: "WRO",
    to: "KAT",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "First Class",
    logo: "assets/img/flight/thumb/lot-logo.png",
    price: 100
  },
  {
    id: 5,
    name: "Iberia",
    way: "roundtrip",
    totaltime: "1h 10m",
    departure: "19:35",
    arriving: "20:45",
    from: "MAD",
    to: "LIS",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/iberia-logo.jpg",
    price: 130
  },
  {
    id: 6,
    name: "KLM",
    way: "roundtrip",
    totaltime: "0h 40m",
    departure: "19:35",
    arriving: "20:15",
    from: "AMS",
    to: "PAR",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Premium Economy",
    logo: "assets/img/flight/thumb/klm-logo.jpg",
    price: 190
  },
  {
    id: 7,
    name: "LATAM",
    way: "roundtrip",
    totaltime: "2h 15m",
    departure: "19:35",
    arriving: "21:50",
    from: "KAT",
    to: "MAD",
    steps: "1 Stop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/latam-logo.jpg",
    price: 190
  },
  {
    id: 8,
    name: "Lufthansa",
    way: "roundtrip",
    totaltime: "4h 15m",
    departure: "19:35",
    arriving: "23:50",
    from: "PAR",
    to: "NYC",
    steps: "2 Stops",
    airplane: "Airbus A380",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/lufthansa-logo.jpg",
    price: 263
  },
  {
    id: 9,
    name: "LOT",
    way: "roundtrip",
    totaltime: "0h 50m",
    departure: "10:35",
    arriving: "11:25",
    from: "WAW",
    to: "KAT",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/lot-logo.png",
    price: 105
  },
  {
    id: 10,
    name: "Emirates",
    way: "roundtrip",
    totaltime: "0h 50m",
    departure: "6:35",
    arriving: "7:25",
    from: "WRO",
    to: "WAW",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Economy/Coach",
    logo: "assets/img/flight/thumb/emirates-logo.jpg",
    price: 130
  },
  {
    id: 11,
    name: "LOT",
    way: "roundtrip",
    totaltime: "0h 50m",
    departure: "12:35",
    arriving: "13:25",
    from: "WAW",
    to: "WRO",
    steps: "Nonstop",
    airplane: "Airbus A320",
    class: "Premium Economy",
    logo: "assets/img/flight/thumb/lot-logo.png",
    price: 160
  }
]
